version: '3.8'

services:
  db:
    image: postgres:16.3
    container_name: dishdash_postgres
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: dishdash
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - dishdash_network

networks:
  dishdash_network:
    driver: bridge

volumes:
  postgres_data:
