version: '3.8'

services:
  db:
    image: postgres:16.3
    container_name: dishdash_postgres
    environment:
      POSTGRES_USER: dishdash
      POSTGRES_PASSWORD: dishdash_pass
      POSTGRES_DB: dishdash
    ports:
      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - dishdash_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

networks:
  dishdash_network:
    driver: bridge

volumes:
  postgres_data:

  redis-data:
