name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build all modules with Maven
        run: mvn -B install

      - name: Get discovery JAR name
        id: discovery_jar
        run: echo "DISCOVERY_JAR_NAME=$(ls discovery/target/*.jar)" >> $GITHUB_ENV

      - name: Get authentication JAR name
        id: auth_jar
        run: echo "AUTHENTICATION_JAR_NAME=$(ls authentication/target/*.jar)" >> $GITHUB_ENV

      - name: Get order JAR name
        id: order_jar
        run: echo "ORDER_JAR_NAME=$(ls order/target/*.jar)" >> $GITHUB_ENV

      - name: Get gateway JAR name
        id: gateway_jar
        run: echo "GATEWAY_JAR_NAME=$(ls gateway/target/*.jar)" >> $GITHUB_ENV

      - name: Get user JAR name
        id: user_jar
        run: echo "USER_JAR_NAME=$(ls user/target/*.jar)" >> $GITHUB_ENV

      - name: Get delivery JAR name
        id: delivery_jar
        run: echo "DELIVERY_JAR_NAME=$(ls delivery/target/*.jar)" >> $GITHUB_ENV

      - name: Get product JAR name
        id: product_jar
        run: echo "PRODUCT_JAR_NAME=$(ls product/target/*.jar)" >> $GITHUB_ENV

      - name: Get payment JAR name
        id: payment_jar
        run: echo "PAYMENT_JAR_NAME=$(ls payment/target/*.jar)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        run: |
          docker run --privileged --rm tonistiigi/binfmt --install all
          docker buildx create --use --name mybuilder
          docker buildx inspect --bootstrap

      - name: Build and Push authentication Docker Image
        run: |
          docker buildx build --builder mybuilder --platform linux/amd64,linux/arm64 \
            --build-arg JAR_FILE=${{ env.AUTHENTICATION_JAR_NAME }} \
            -t mirzaeimahdi409/dish_dash_authentication:latest \
            --push \
            -f ./authentication/DockerFile ./authentication

      - name: Build and Push discovery Docker Image
        run: |
          docker buildx build --builder mybuilder --platform linux/amd64,linux/arm64 \
            --build-arg JAR_FILE=${{ env.DISCOVERY_JAR_NAME }} \
            -t mirzaeimahdi409/dish_dash_discovery:latest \
            --push \
            -f ./discovery/DockerFile ./discovery

      - name: Build and Push order Docker Image
        run: |
          docker buildx build --builder mybuilder --platform linux/amd64,linux/arm64 \
            --build-arg JAR_FILE=${{ env.ORDER_JAR_NAME }} \
            -t mirzaeimahdi409/dish_dash_order:latest \
            --push \
            -f ./order/DockerFile ./order

      - name: Build and Push gateway Docker Image
        run: |
          docker buildx build --builder mybuilder --platform linux/amd64,linux/arm64 \
            --build-arg JAR_FILE=${{ env.GATEWAY_JAR_NAME }} \
            -t mirzaeimahdi409/dish_dash_gateway:latest \
            --push \
            -f ./gateway/DockerFile ./gateway

      - name: Build and Push user Docker Image
        run: |
          docker buildx build --builder mybuilder --platform linux/amd64,linux/arm64 \
            --build-arg JAR_FILE=${{ env.USER_JAR_NAME }} \
            -t mirzaeimahdi409/dish_dash_user:latest \
            --push \
            -f ./user/DockerFile ./user

      - name: Build and Push delivery Docker Image
        run: |
          docker buildx build --builder mybuilder --platform linux/amd64,linux/arm64 \
            --build-arg JAR_FILE=${{ env.DELIVERY_JAR_NAME }} \
            -t mirzaeimahdi409/dish_dash_delivery:latest \
            --push \
            -f ./delivery/DockerFile ./delivery

      - name: Build and Push product Docker Image
        run: |
          docker buildx build --builder mybuilder --platform linux/amd64,linux/arm64 \
            --build-arg JAR_FILE=${{ env.PRODUCT_JAR_NAME }} \
            -t mirzaeimahdi409/dish_dash_product:latest \
            --push \
            -f ./product/DockerFile ./product

      - name: Build and Push payment Docker Image
        run: |
          docker buildx build --builder mybuilder --platform linux/amd64,linux/arm64 \
            --build-arg JAR_FILE=${{ env.PAYMENT_JAR_NAME }} \
            -t mirzaeimahdi409/dish_dash_payment:latest \
            --push \
            -f ./payment/DockerFile ./payment

      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "docker-compose.yml"
          target: "/root/dish_dash"

      - name: Deploy with SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /root/dish_dash
            docker compose down
            docker compose pull
            docker compose up -d